[project]
requires-python = ">=3.10"
dependencies = [
]

[tool.poetry]
name = "text-to-voice"
version = "0.1.0"
description = "API para convertir texto a voz"
authors = [
    "Omar Regino <omarjrz21@gmail.com>"
]
readme = "README.md"
packages = [{include = "text_to_voice", from = "src"}]


[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
pyttsx3 = "^2.90"
PyPDF2 = "^3.0.1"
python-multipart = "^0.0.6"
pydantic = "^2.6.0"
pydantic-settings = "^2.1.0"
textblob = "^0.19.0"
langdetect = "^1.0.9"
pyspellchecker = "^0.8.2"
spacy = "^3.7.2"
markitdown = {version = "^0.1.0", extras = ["pdf"]}
torch = "^2.6.0"
torchaudio = "^2.6.0"
np = "^1.0.2"
transformers = "^4.37.0"
datasets = "^2.16.0"
soundfile = "^0.12.1"
sentencepiece = "^0.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^24.1.0"
isort = "^5.13.0"
flake8 = "^7.0.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
